; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = left, right, left_pressure_oled

[esp32_base]
platform = espressif32@6
board = seeed_xiao_esp32s3
board_build.partitions = default_8MB.csv
build_unflags = -std=gnu++11
framework = arduino
upload_protocol = esptool
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps =
	roboticsbrno/ServoESP32@^1.1.1
	bblanchon/ArduinoJson@^7.4.2
	https://github.com/reivaxy/XOLEDDisplay/archive/refs/tags/v1.0.tar.gz
	thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.3.0

[env:proto]
extends = esp32_base
build_flags = !python gitVersion.py -std=gnu++17  -DCORE_DEBUG_LEVEL=3
upload_port = COM28
monitor_port = COM28

[env:right]
extends = esp32_base
build_flags = !python gitVersion.py -std=gnu++17  -DCORE_DEBUG_LEVEL=3
upload_port = COM15
monitor_port = COM15

[env:left_pressure_oled]
extends = esp32_base
build_flags = !python gitVersion.py -std=gnu++17  -DLEFT_HAND  -DCORE_DEBUG_LEVEL=3 -DWITH_SENSOR -DWITH_OLED_DISPLAY
upload_port = COM11
monitor_port = COM11

[env:left]
extends = esp32_base
build_flags = !python gitVersion.py -std=gnu++17  -DLEFT_HAND -DCORE_DEBUG_LEVEL=3
upload_port = COM11
monitor_port = COM11

[env:left_display]
extends = esp32_base
build_flags = !python gitVersion.py -std=gnu++17  -DLEFT_HAND -DCORE_DEBUG_LEVEL=3 -DWITH_OLED_DISPLAY
upload_port = COM11
monitor_port = COM11

# These are demo build configuration, they will run a predefined sequence of movements on the hand.
# It can be useful for testing and demos, but can be flaky if used along with the apps (which also have a demo mode)
[env:demo_right]
extends = esp32_base
build_flags = !python gitVersion.py -std=gnu++17  -DDEMO -DCORE_DEBUG_LEVEL=3
upload_port = COM15
monitor_port = COM15

[env:demo_left]
extends = esp32_base
build_flags = !python gitVersion.py -std=gnu++17  -DLEFT_HAND -DDEMO -DCORE_DEBUG_LEVEL=3
upload_port = COM11
monitor_port = COM11

[env:tests]
platform = native
test_framework = unity
test_build_src = yes
build_flags =
    -std=c++17
    !python -c "import os; print('-I' + os.path.abspath('test/mocks').replace(chr(92), '/'))"
build_src_filter = +<*> -<*main.cpp> -<*BtServer.cpp> -<*OtaWifiUploadServer.cpp>

[env]

